{% set version = "3.9.1" %}

package:
  name: libgdal-core
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: aff3086fee75f5773e33a5598df98d8a4d10be411f777d3ce23584b21d8171ca

build:
  number: 5
  skip_compile_pyc:
    - share/bash-completion/completions/*.py
  skip: true  # [ppc64le]
  run_exports:
    # no idea, going with minor pin
    - {{ pin_subpackage('libgdal-core', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - pkg-config >=0.21  # [not win]
    - make  # [not win]
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - swig
  host:
    - blosc
    - cfitsio
    - expat
    - freexl
    - geos
    - geotiff
    - giflib  # [not win]
    - hdf4
    - hdf5
    - libjpeg-turbo
    - json-c  # [not win]
    - kealib
    - lerc
    - libarchive
    - libaec  # for GRIB driver
    - libcurl
    - libdeflate
    - libiconv
    - libkml
    - libnetcdf
    - libpng
    - libpq
    - libspatialite
    - libtiff
    - libuuid  # [linux]
    - libwebp-base
    - libxml2
    - lz4-c
    - openssl
    - pcre2
    - poppler
    - proj
    # qhull disabled because of https://github.com/conda-forge/qgis-feedstock/issues/284#issuecomment-1356490896
    # - qhull
    - sqlite
    - tiledb
    - xerces-c
    - xz
    - zlib
    - zstd
  run:
    - poppler
    - postgresql

test:
  files:
    - test_data
    - run_test.bat
    - run_test.sh

outputs:
  - name: libgdal-core

  - name: libgdal-arrow-parquet
    script: build_arrow_parquet.sh  # [unix]
    script: build_arrow_parquet.bat  # [win]
    requirements:
      build:
        - cmake
        # ranlib used at install time
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        # libstdc++ is needed in requirements/run
        - {{ compiler('cxx') }}
        - pkg-config  # [not win]
        - make  # [unix]
        - ninja  # [win]
      host:
        - {{ pin_subpackage('libgdal-core', exact=True) }}
        - libarrow
        - libarrow-dataset  # [libarrow != 13]
        - libparquet        # [libarrow != 13]
      run:
        - libgdal-core >={{ ".".join(version.split(".")[:2]) }}
    test:
      files:
        - test_arrow_parquet.sh   # [unix]
        - test_arrow_parquet.bat  # [win]
      commands:
        - sh test_arrow_parquet.sh   # [unix]
        - test_arrow_parquet.bat  # [win]
    about:
      summary: Arrow and Parquet drivers for the Geospatial Data Abstraction Library (GDAL)
      license: MIT
      license_file: LICENSE.TXT

  - name: libgdal-openjpeg
    script: build_openjpeg.sh  # [unix]
    script: build_openjpeg.bat  # [win]
    requirements:
      build:
        - cmake
        # ranlib used at install time
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        # libstdc++ is needed in requirements/run
        - {{ compiler('cxx') }}
        - pkg-config  # [not win]
        - make  # [unix]
        - ninja  # [win]
      host:
        - {{ pin_subpackage('libgdal-core', exact=True) }}
        # plugin specific
        - openjpeg
      run:
        - libgdal-core >={{ ".".join(version.split(".")[:2]) }}
    test:
      files:
        - test_arrow_parquet.sh   # [unix]
        - test_arrow_parquet.bat  # [win]
      commands:
        - sh test_arrow_parquet.sh   # [unix]
        - test_arrow_parquet.bat  # [win]
    about:
      summary: Arrow and Parquet drivers for the Geospatial Data Abstraction Library (GDAL)
      license: MIT
      license_file: LICENSE.TXT

  - name: libgdal
    requirements:
      run:
        - {{ pin_subpackage('libgdal-core', exact=True) }}

  - name: gdal
    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]
    build:
      skip_compile_pyc:
        - share/bash-completion/completions/*.py
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja  # [win]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - swig
      host:
        - python
        - pip
        - numpy
        - {{ pin_subpackage('libgdal-core', exact=True) }}
        # Workaround to prevent run depending on "libgfortran5 9.3.0" despite "hdf5"
        # having not been migrated yet causing conflicts with the "libgdal" output
        # See: https://github.com/conda-forge/gdal-feedstock/pull/415
        - hdf5
        - libxml2
        # Workaround to prevent conflicts seen in
        #  https://github.com/conda-forge/gdal-feedstock/pull/543
        - openssl
      run:
        - python
        - {{ pin_subpackage('libgdal-core', exact=True) }}
    test:
      files:
        - test_data
        - extra_tests.py
        - test_python.py
        - test_script_exist.bat
      requires:
        - libgdal-openjpeg
      imports:
        - osgeo
        - osgeo.ogr
        - osgeo.gdal
        - osgeo._gdal
        - osgeo._gdalconst
        - osgeo._ogr
        - osgeo._osr
      commands:
        - python test_python.py
        # Check that Python-implemented GDAL utilities are available with .py extension, as documented
        - gdal2tiles.py --help
        - gdal2xyz.py --help
        - gdal_calc.py --help
        - gdal_edit.py --help
        - gdal_fillnodata.py --help
        - gdal_merge.py --help
        - gdal_pansharpen.py --help
        - gdal_polygonize.py --help
        - gdal_proximity.py --help
        - gdal_retile.py --help
        - gdal_sieve.py --help
        - gdalattachpct.py --help
        - gdalcompare.py --help
        - gdalmove.py --help
        - pct2rgb.py --help
        - rgb2pct.py --help
        - ogrmerge.py --help
        - ogr_layer_algebra.py --help
        # Check that the utilities are available as entry points without extension, see:
        # https://github.com/conda-forge/gdal-feedstock/issues/834
        # https://github.com/OSGeo/gdal/pull/8718
        # https://github.com/OSGeo/gdal/issues/8811
        - gdal2tiles --help
        - gdal2xyz --help
        - gdal_calc --help
        - gdal_edit --help
        - gdal_fillnodata --help
        - gdal_merge --help
        - gdal_pansharpen --help
        - gdal_polygonize --help
        - gdal_proximity --help
        - gdal_retile --help
        - gdal_sieve --help
        - gdalattachpct --help
        - gdalcompare --help
        - gdalmove --help
        - pct2rgb --help
        - rgb2pct --help
        - ogrmerge --help
        - ogr_layer_algebra --help
      about:
        summary: Python wrapper for the Geospatial Data Abstraction Library (GDAL)
        license: MIT
        license_file: LICENSE.TXT

about:
  home: http://www.gdal.org
  license: MIT
  license_file: LICENSE.TXT
  summary: |
    GDAL is a translator library for raster and vector geospatial data formats that is released under an
    X/MIT style Open Source license by the Open Source Geospatial Foundation.

extra:
  feedstock-name: gdal
  recipe-maintainers:
    - zklaus
    - akrherz
    - gillins
    - kmuehlbauer
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
